[package]
name = "configfs-tsm"
version = "0.0.1"
edition = "2021"
authors   =['Entropy Cryptography <engineering@entropy.xyz>']
homepage  ='https://entropy.xyz/'
license   ='AGPL-3.0-or-later'
repository='https://github.com/entropyxyz/configfs-tsm'

[dependencies]
